Master now builds, edited daysInMonthArray method to not rely on 52 weeks as this is inacurate enough to cause issues when moving between months. New error found that does not cause crashing:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.qalendar, PID: 13338
    java.lang.IllegalStateException: Could not find method dailyAction(View) in a parent or ancestor Context for android:onClick attribute defined on view class androidx.appcompat.widget.AppCompatButton
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:506)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:464)
        at android.view.View.performClick(View.java:7659)
        at android.view.View.performClickInternal(View.java:7636)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:30076)
        at android.os.Handler.handleCallback(Handler.java:958)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:294)
        at android.app.ActivityThread.main(ActivityThread.java:8180)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
I/Process: Sending signal. PID: 13338 SIG: 9